@startuml
title GlueJobの処理フロー

start
:S3バケットのオブジェクト一覧を取得;

repeat
    :オブジェクト名を取得;
    #0f58a8:変換対象のオブジェクト名か確認;
    #0f58a8:変換処理後に移動するためのオブジェクト名を取得;
    #0f58a8:dataframeを作成;
    partition "変換処理" {
        #0f58a8:dataframeにフォーマットバージョンを追加;
        #0f58a8:dataframeに日付情報を追加;
        #0f58a8:日付情報の列にUTC→JST処理;
        #0f58a8:品番情報の列に不要データが含まれている場合、行ごと除外;
        #0f58a8:文字列型の列に半角・全角統一処理;
    }
    if (変換処理結果) then (処理成功)
        :変換データをsnappy.parquetにしてLoadフォルダへ移動;
        :元データをrawフォルダへ移動;
    else (処理失敗)
        :元データをerrorフォルダへ移動;
        :グローバルのエラーフラグをON;
    endif
repeat while (次のオブジェクト名へ)

if (エラーフラグ) then (ON)
    :Jobを失敗させて通知発行;
endif

end

@enduml